### ISSUE TITLE
Undefined variable: input in send.php on line 11

### ISSUE THREAD

**Issue by scorpio2k2** [geek-at/gammu-php#4]
Hello,
When I try to send an SMS: 
Undefined variable: input in send.php on line 11

get.php works fine.

PHP 7.4.3

**Comment by geotibi** [comment]
Have you suceed with this? I'm getting the same error

**Comment by SirPrikol** [comment]
2 questions

First, not send SMS if phone=+1234567....
Second, not send cyrillic

**Comment by 044atlanticdrift** [comment]
hello. why the command curl http://ip.of.your.pi/send.php?phone=07921XXXXXX&text=Testmessage doesn't work? it returns "[1] 3883" but there's nothing in recieved messages on my phone. how to fix that?
